export const contractsHints = {
  contractId: 'Unique identifier for a smart contract instance that lives on the blockchain.',
  createdBy: 'Keyblock height and exact date and time when the smart contract was created.',
  hash: 'The transaction hash of a ContractCreateTx that was executed to create the smart contract on the blockchain.',
  creator: 'Account that created the smart contract on the blockchain.',
  status: 'Status of the transaction.',
  smartContract: 'Unique identifier for a smart contract instance that lives on the blockchain.',
  caller: 'Account that called the smart contract.',
  amount: 'Amount of AE coins that were transferred to the smart contract address.',
  entrypoint: 'The entrypoint of the smart contract that has been called.',
  arguments: 'Arguments that were passed to the entrypoint.',
  return: 'Value that was returned by the entrypoint.',
  gasLimit: 'Maximum amount of gas to be consumed by this transaction.',
  gasPrice: 'Price for one unit of gas.',
  gasUsed: 'Amount of gas that was consumed by this transaction.',
  gasCost: 'The amount of AE paid for the execution of the contract entrypoint.',
}
