export const contractsHints = {
  contractId: 'Unique identifier for a smart contract instance that lives on the blockchain.',
  contractCreated: 'Keyblock height and exact date and time when the smart contract was created.',
  contractTxHash: 'The transaction hash of a ContractCreateTx that was executed to create the smart contract on the blockchain.',
  contractCreator: 'Account that created the smart contract.',
  bytecode: 'Pre-compiled code of the smart contract.',
  contractsAccount: 'The address where the smart contract is located. To be used if a smart contract is already deployed.',
  contractsAccountBalance: 'smart contract account balance. Balance is needed to execute "payable" functions.',
  contractCalls: 'Amount of calls to the smart contract.',
  apiLinks: 'Links to sources of the smart contract data.',
  callTransactionsHash: 'Unique identifier of ContractCallTx which represents call to smart contract function.',
  callTransactionsTime: 'Estimated date, time and block height when the smart contract was called.',
  callTransactionsCaller: 'Account that called the smart contract.',
  callTransactionsEntryPoint: 'Name of the smart contract function that was called.',
  eventsCallTransaction: 'Unique identifier of ContractCallTx which emitted the event.',
  eventsCreated: 'Estimated date, time and block height when the smart contract had emitted the event.',
  eventsName: 'Name of the emitted event.',
  eventsArguments: 'The payload of the emitted event.',
}
