export const namesHints = {
  name: 'Unique identifier that may be configured to point to accounts, contracts or oracles.',
  nameInAuction: 'Unique identifier that may be configured to point to accounts, contracts or oracles. Names shorter than 13 characters are always auctioned.',
  expires: 'Keyblock height and estimated date and time when the auction ends and the name will be activated and owned by the highest bidder. After expiration, the name enters into a revoked state and can be claimed again after a fixed timeout of 2016 keyblocks.',
  buyer: 'Address of the account which paid for the Name and price of the Name.',
  owner: 'Account that paid the shown price to claim the name.',
  pointsTo: 'The account the name points to.',
  highestBid: 'Account of the highest bidder and the price of the highest bid.',
  bidCount: 'Amount of bids in the auction.',
  ends: 'Keyblock height and estimated date and time when the auction ends.',
  expired: 'Keyblock height and estimated date and time when the Name was detached from the account. After expiration, the name entered into a revoked state and can be claimed again after a fixed timeout of 2016 keyblocks.',
  lastBuyer: 'Account that previously paid the shown price to claim the name.',
  lastOwner: 'Last owner of the Name.',
  bidder: 'Account of the highest bidder.',
  bid: 'Price of the highest bid.',
  ownedSince: 'Keyblock height and estimated date and time when the account became the owner of the Name.',
  status: 'Current state of the Name. The possible states are: Active, In Auction or Expired.',
  customPointers: 'User-defined pointers with custom keys.',
  accountPointer: 'The account that the Name points to.',
  channelPointer: 'The State Channel that the Name points to.',
  contractPointer: 'The Smart Contract that the Name points to.',
  oraclePointer: 'The Oracle that the Name points to.',
  eventTransactionHash: 'Transaction hash of the Name event.',
  eventTime: 'Keyblock height and estimated date and time when the event was triggered.',
  activity: 'Type of event that was triggered.',
  recentlyActivatedData: 'The Name and its owner who claimed it.',
  activationPrice: 'Amount of AE coins paid for the name activation at fixed price or via auction. These AE coins are burned.',
  activationTime: 'Keyblock height and date and time when the Name was activated.',
  nameAndHighestBidder: 'Auctioned Name and its highest bidder.',
}
