export const stateChannelsHints = {
  stateChannelId: 'Unique identifier of the state channel.',
  status: 'While the status is "Open", the state channel participants can execute an unlimited amount of transactions off-chain with instant finality. The status will be "Closed" if one of the participants executes either a ChannelCloseMutualTx or a ChannelSettleTx',
  participants: 'Initiator is the account that paid the fees to create the state channel. Responder is the account that joined the state channel.',
  onChainUpdates: 'Amount of on-chain transactions related to the state channel. Participants can for example deposit to, withdraw from or provide a snapshot of the state channel to the chain.',
  locked: 'Current amount of AE coins deposited to the state channel by both participants. While the state channel is open and no snapshot is provided to the chain, only the participants know who owns a specific amount of the deposited AE coins.',
  lastUpdated: 'Keyblock height and estimated date and time of the last on-chain interaction with the state channel.',
  lastTxType: 'Type of the last on-chain transaction related to the state channel.',
  apiLinks: 'Links to sources of the smart contract data.',
  createTransaction: 'The transaction that created the state channel.',
  initialAmount: 'The total amount of AE coins that have initially been deposited to the state channel by initiator and responder combined.',
  initiator: 'The account that initiated the creation of the state channel and covered the fees for its creation.',
  responder: 'The participating account that joined the state channel.',
  lastKnownRound: 'Participants can for example protect themselves from being cheated on by providing a snapshot from the latest off-chain round to the chain.',
  slashedRound: 'The round in which the slash was triggered.',
  slashedBy: 'The account that slashed (disputed) malicious ChannelCloseSoloTx or ChannelForceProgressTx.',
  initiatorAmount: 'The amount of AE coins that was redistributed back to initiator.',
  responderAmount: 'The amount of AE coins that was redistributed back to responder.',
  settledBy: 'The account that initiated the redistribution process.',
  snapshotRound: 'The round in which the state channel was snapshotted.',
  snapshottedBy: 'The account that initated the snapshot of the state channel.',
  forceProgressRound: 'The round in which the state channel was forced to progress.',
  forcedBy: 'The account that requested the the state channel to progress.',
  depositor: 'Account that deposited funds to the state channel.',
  depositRound: 'The round in which the deposit was made to the state channel.',
  depositAmount: 'Amount deposited to the state channels.',
  withdrawRound: 'The round in which the withdrawal was made from the state channel.',
  withdrawAmount: 'Amount withdrawn from the state channel.',
  withdrawRecipient: 'Account that received the withdrawn funds.',
  initiatorDelegates: '',
  responderDelegates: '',
  lockPeriod: '',
  closeRound: 'The round in which the state channel was closed.',
  closeProposedBy: 'The account that proposed the state channel to be closed.',
  sentBy: 'The account that initiated the channel closure.',
  channelReserve: 'The amount of AE coins that is reserved for the channel.',

}
