export const stateChannelsHints = {
  stateChannel: 'A state channel allows the gas-free execution of smart contracts and transactions, privately and with the speed of light, while still being able to escalate on-chain in case of disagreement.',
  stateChannelId: 'Unique identifier of the state channel.',
  status: 'While the status is "Open", the state channel participants can execute unlimited transactions off-chain with instant finality. The status will be "Closed" if one of the participants executes either a ChannelCloseMutualTx or a ChannelSettleTx',
  participants: 'Initiator is the account that paid the fees to create the state channel. Responder is the account that joined the state channel.',
  onChainUpdates: 'Amount of on-chain transactions related to the state channel. Participants can for example deposit to, withdraw from, or provide a snapshot of the state channel to the chain.',
  locked: 'Current amount of AE coins deposited to the state channel by both participants. While the state channel is open and no snapshot is provided to the chain, only the participants know who owns a specific amount of the deposited AE coins.',
  lastUpdatedHeight: 'Keyblock height of the last on-chain interaction with the state channel.',
  lastUpdated: 'Exact date and time of the last on-chain interaction with the state channel.',
  lastTxType: 'Type of the last on-chain transaction related to the state channel.',
  apiLinks: 'Links to sources of the smart contract data.',
  createTransaction: 'The transaction that created the state channel.',
  initialAmount: 'The total amount of AE coins that have initially been deposited to the state channel by initiator and responder combined.',
  initiator: 'The account that initiated the creation of the state channel and covered the fees for its creation.',
  responder: 'The participating account that joined the state channel.',
  lastKnownRound: 'Participants can protect themselves from being cheated on by providing a snapshot from the latest off-chain round to the chain.',
  slashedRound: 'The round in which the slash was triggered.',
  slashedBy: 'The account that slashed (disputed) malicious ChannelCloseSoloTx or ChannelForceProgressTx.',
  initiatorCreateAmount: 'Unsigned amount of coins the initiator commits to the channel.',
  initiatorCloseAmount: 'Final balance for the initiator.',
  initiatorSettleAmount: 'Unsigned amount of coins the initiator gets from the channel.',
  responderCreateAmount: 'Unsigned amount of coins the responder commits to the channel.',
  responderCloseAmount: 'Final balance for the responder.',
  responderSettleAmount: 'Unsigned amount of coins the responder gets from the channel.',
  settledBy: 'Participant of the state channel that posted the settling transaction.',
  snapshotRound: 'Channel snapshot\'s round.',
  snapshottedBy: 'The account that initiated the snapshot of the state channel.',
  forceProgressRound: 'The round in which the state channel was forced to progress.',
  forcedBy: 'Participant or a delegate of the channel that posts the force progress transaction.',
  depositor: 'The account that deposited funds to the state channel.',
  depositRound: 'The channel\'s internal round that applies the deposit.',
  depositAmount: 'Amount deposited to the state channel.',
  withdrawRound: 'The channel\'s internal round that applies the withdraw.',
  withdrawAmount: 'Amount withdrawn from the state channel.',
  withdrawRecipient: 'The account that received the withdrawn funds.',
  initiatorDelegates: 'List of delegate account ids by the initiator. The delegates play a role in the solo closing sequence.',
  responderDelegates: 'List of delegate account ids by the responder. The delegates play a role in the solo closing sequence.',
  lockPeriod: 'Period for disputes after solo operations.',
  closeRound: 'The round in which the state channel was proposed to be closed.',
  closeProposedBy: 'The participant of the state channel that posts the closing transaction.',
  sentBy: 'State channel participant or delegate that posts the slashing transaction.',
  channelReserve: 'The minimum amount of AE coins that must remain locked in any of the off-chain accounts in the state channel.',
}
