name: Production pipelines - mainnet

on:
  push:
    branches:
      - main

env:
  ENV: "prd"
  APP: "aescan"

concurrency: aescan_production_environment-${{ github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    environment: production
    name: Production Pipeline æScan Frontend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Get tags
        run: git fetch --tags origin

      - name: Get latest release tag
        shell: bash
        id: release_tag
        run: echo TAG=$(git describe --tags HEAD --abbrev=0) >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.ENV }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ENV }}-buildx

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/aescan
          tags: |
            type=raw,value=${{ steps.release_tag.outputs.TAG }}

      - name: Create dotenv
        run: |
          echo APP_VERSION=$(git describe --tags --abbrev=0) >> .env

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: prd
          persist-credentials: false
          fetch-depth: 0

      - name: Production Deploy
        uses: aeternity/ae-github-actions/argocd-deploy@v4
        with:
          git-sha: ${{ steps.git-sha.outputs.GIT_SHA }}
          url-prefix: ${{ steps.release_tag.outputs.TAG }}
          env: ${{ env.ENV }}
          app: ${{ env.APP }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: aeternity/gitops-apps
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: prd
